#!/bin/bash

UCOSLAM_SOURCE_DIR=$HOME/dev/ucoslam/ucoslam-open
UCOSLAM_CONFIG_DIR=$UCOSLAM_SOURCE_DIR/config
UCOSLAM_INSTALL_DIR=$UCOSLAM_SOURCE_DIR/../install
UCOSLAM_BIN_DIR=$UCOSLAM_INSTALL_DIR/bin

ORB_VOCABULARY=$UCOSLAM_CONFIG_DIR/orb.fbow

#CAMERA_NAME=camera
CAMERA_NAME=${HOSTNAME}

export LD_LIBRARY_PATH=$UCOSLAM_INSTALL_DIR/lib:$LD_LIBRARY_PATH
export PATH=$UCOSLAM_INSTALL_DIR/bin:$PATH
